### ISSUE TITLE
All types of Bytes should be available in hex

### ISSUE THREAD

**Issue by TheAlgorythm** [jonasbb/serde_with#300]
I have a `[u8, N]` and want to deserialize it in the hex format. Base64 would also be cool but also way more complex.

**Comment by jonasbb** [comment]
Hi, thanks for the interest.
It seems that serialization already works with the existing `Hex` type, only deserialization is impossible since there is no `[u8; N]: From<Vec<u8>>` implementation.

Even disconnected from this issue, it might be worthwhile to see if the `DeserializeAs` implementation can be changed to something like this, since that would allow `TryFrom` in addition to all currently existing `From` implementations.
This also does not work for arrays though, since the `TryFrom` error does not implement `Display`.
```rust
impl<'de, T, E, FORMAT> DeserializeAs<'de, T> for Hex<FORMAT>
where
    T: TryFrom<Vec<u8>, Error = E>,
    E: Display,
    FORMAT: Format,
```

Therefore, I think the only way forward is to add another `Hex`-like type especially for array, a `HexArray`. Do you want to contribute this? The implementation in `hex.rs` is quite simple.
If you want to contribute base64 too, I would be happy to accept that too. Implementation wise it shouldn't differ too much from the hex type, except that there are different base64 character sets. But they can always be added later.

**Comment by jonasbb** [comment]
I just released a new version of the crate with this fix included. Thanks for implementing the fix.
