### ISSUE TITLE
Derive SerializeAs/DeserializeAs for remote impls?

### ISSUE THREAD

**Issue by leo60228** [jonasbb/serde_with#397]
The examples for using serde_as with remote impls look like a major ergonomic improvement, but avoiding the SerializeAs/DeserializeAs boilerplate would help even more.

**Comment by jonasbb** [comment]
Hi, this sounds like a reasonable extension. Could you please explain how you imagine it should work from the user perspective, and maybe also to what code it should expand to? A tiny code snippet of the macro invocation would be great. This would help me figure out how it should work. A set of `macro_rules` macros is likely the easiest. It needs to handle cases where you want either `SerializeAs` or `DeserializeAs`, but not both. That can be done with additional macros.

**Comment by leo60228** [comment]
Taking an example from the docs as a starting point:

```rust
// Pretend that this is somebody else's crate, not a module.
mod other_crate {
    // Neither Serde nor the other crate provides Serialize and Deserialize
    // impls for this struct.
    pub struct Duration {
        pub secs: i64,
        pub nanos: i32,
    }
}

////////////////////////////////////////////////////////////////////////////////

use other_crate::Duration;

// Serde calls this the definition of the remote type. It is just a copy of the
// remote data structure. The `remote` attribute gives the path to the actual
// type we intend to derive code for.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(remote = "Duration")]
struct DurationDef {
    secs: i64,
    nanos: i32,
}

impl SerializeAs<Duration> for DurationDef {
    fn serialize_as<S>(value: &Duration, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {  
        DurationDef::serialize(value, serializer)
    }
}

#[serde_as]
#[derive(serde::Serialize)]
struct Data {
    #[serde_as(as = "Vec<DurationDef>")]
    vec: Vec<Duration>,
}
```
It feels like it should be possible to just have:
```rust
use other_crate::Duration;

// Serde calls this the definition of the remote type. It is just a copy of the
// remote data structure. The `remote` attribute gives the path to the actual
// type we intend to derive code for.
#[derive(serde::Serialize, serde::Deserialize, SerializeAs)]
#[serde(remote = "Duration")]
struct DurationDef {
    secs: i64,
    nanos: i32,
}

#[serde_as]
#[derive(serde::Serialize)]
struct Data {
    #[serde_as(as = "Vec<DurationDef>")]
    vec: Vec<Duration>,
}
```
The type to serialize as could just be taken from the `#[serde(remote)]` attribute, but it *might* make sense to have a separate attribute for more niche usecases where the `serialize`/`deserialize` functions don't come from serde's derives.

**Comment by jonasbb** [comment]
Thanks for the explanation. A derive macro seems easy and flexible to use. If you only need one of the two traits, you can do that.

--- 

Initially, I thought of something like this. It has the downside of duplicating the type names.

```rust
serde_with::serde_as_impls!(DurationDef Duration);
// i.e., localtype remotetype
```

But it could be extended to support the module form, which you can use with `serde(with = "...")`:

```rust
mod bytes_as_hex {
    fn serialize() {}
    fn deserialize() {}
}

struct BytesAsHex;
serde_with::serde_as_impls!(BytesAsHex Vec<u8> bytes_as_hex);
// i.e., localtype remotetype convertion_module
```

Another downside is that it now becomes awkward to only have one of the two traits, likely requiring `serde_as_impls_de` and `serde_as_impls_ser` variants to solve.

---

Since a local type is always necessary for `serde_as`, maybe the module support can also be added to the derive macro.

```rust
mod bytes_as_hex {
    fn serialize() {}
    fn deserialize() {}
}

#[derive(SerializeAs)]
#[serialize_as(type = Vec<u8>, module = bytes_as_hex)]
struct BytesAsHex;
```

**Comment by jonasbb** [comment]
I tried to implement the derives but failed to find a solution to find the correct trait bounds. When using the remote derive, the `serialize` and `deserialize` functions are inherent functions on the local type, but they will have further constraints for generics. Unfortunately, serde has many rules how to build the trait bounds, so I feel reimplementing them is too much for this crate. A reimplementation might also drift, so I don't think this is a good solution. For example, you have `bound` on the container or field and various `with` attributes which need to be understood.

Since the two functions are inherent to the type, they cannot be used in  `where`-bounds. This thus prevents me from directly relying on them for the heavy lifting.

I don't see it as helpful to only try to support types without generics. They might be a little bit easier, but a half-working implementation which just stops working after doing reasonable changes to your type feels worse than no derive. But given that `bound` can be applied to the container, this might not even solve the problem in the first place.

For now, I am going to close this issue since I see no way to properly implement it. Maybe part of the serde derives are better reusable in the future, then this might be solvable.
