### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by pwnorbitals** [jonasbb/serde_with#435]
It looks like this crate doesn’t support `no_std`, making it harder to serialize long byte arrays in embedded environments. Is this on the roadmap ?

**Comment by jonasbb** [comment]
Hi @pwnorbitals, `no_std` support is currently not on the roadmap, since nobody requested it before. However, I gladly review PRs adding support and helping implement that feature. I never used `no_std`, so I could really use some help setting up features and testing.

Generally, I don't see a problem with `no_std` support. serde fully supports `no_std` and `rustversion` can be replaced with a build script to check the compiler version. The newly stabilized weak dependency features should also help here. All other crates are already feature gated, so that those implementations should not cause any problems.
Adding a `std` feature and gating existing functionality behind it is as far as I know a breaking change.

---

Could you maybe expand a bit on what exactly you need or in general expect from a `no_std` crate? Do you need `core`, `core+alloc` or both?
Are there any `SerializeAs` implementations more important? I guess, each implementation could be made `no_std` compatible one by one.

**Comment by jonasbb** [comment]
I started working on this in #444. So far I only changed the imports and feature gated imports and implementations. The changes so far seem relatively unproblematic to me and can probably be merged anyway as future preparations.
To really support `no_std` properly are two main questions to answer and some more work updating macros and dependencies.
1. What is the target where to use `no_std`? Is it only `core or `core`+`alloc`.
2. I need help from someone who understand `no_std` how to test it. Otherwise it is not possible to ensure that macros or dependencies do not depend on `std` in some way. I looked at `serde`, but they only have minimal tests for `no_std` and also no dependencies which could interfere.

**Comment by garbageslam** [comment]
I ran into this today too.

Core only is best, Core + alloc will still be fine for many no_std projects. Generally the more you can minimize your dependencies the better it is for your users.

I can try to offer a PR to help with this, I have a lot of experience moving stuff to no_std

**Comment by garbageslam** [comment]
It looks like you already did a lot of work on this in this commit in master, thank you! https://github.com/jonasbb/serde_with/commit/c9d92269fd493b467ae39ee44b1de92c325669a1

At this point you are still bringing in `extern crate std` unconditionally? https://github.com/jonasbb/serde_with/blob/7d9aebc1096903ea4e29ccdb6ae2f95e897cafde/serde_with/src/lib.rs#L267

For my 2 cents, I think it is worth it to have an `std` feature and allow to turn off `std` for `serde_with`, even if the macros don't fully work that when it is configured that way yet. Because the crate is quite useful even without the macros, and we could make the macros work in a later release of the macros crate. That would have worked for my use-case anyways.

**Comment by jonasbb** [comment]
Thanks for the cbor reference. That seems quite useful. That works as a starting point: testing `--no-default-features` and `--no-default-features --features=alloc`. Some extra testing for all the features would also be good. Probably time to look into cargo hack and see if that makes sense here.

So the steps I see which need to be done are:

1. Add another CI job to `ci.yml` testing with both `--no-default-features` and `--no-default-features --features=alloc`. The job uses a target without std.
2. Add `alloc` and `std` features. Enable `std` by default. `std` should probably also enable alloc. Both features also need to be forwarded to serde.
3. Feature gate all imports and trait implementations on either `alloc` or `std`.

After this, the CI job should pass.

Each optional feature/dependency also needs a check. This means more feature gating where possible and forwarding `alloc`/`std` to dependencies. Where dependencies are not `no_std` compatible including the dependency should just enable the `std` feature.

> Dropping a dependency is never a breaking change.

Dropping a dependency might not be a breaking change, but loosing trait implementations for alloc and std types is.

**Comment by garbageslam** [comment]
> Dropping a dependency might not be a breaking change, but loosing trait implementations for alloc and std types is.

Yes true. But you can put std feature on by default, and then it's not a breaking change

**Comment by jonasbb** [comment]
I created a new PR with the changes as explained above https://github.com/jonasbb/serde_with/pull/469

Currently, this is very bare bones, but ready for testing. I would be very happy to get some feedback if this works or if there is some problem using it in a `no_std` project @garbageslam 
This is still missing update to all optional dependencies and macros are gated behind `std` for now. But these can be changed separately.

**Comment by jonasbb** [comment]
I released new version of `serde_with` with the changes to support `no_std`. I am still hoping for some feedback, either positive (i.e, everything works) or negative (i.e., something incompatible with `no_std`). If you have any problems, please open a new issue.
