### ISSUE TITLE
RUSTSEC-2020-0071: Potential segfault in the time crate #378

### ISSUE THREAD

**Issue by lcmgh** [jonasbb/serde_with#495]
https://github.com/jonasbb/serde_with/issues/378 issue was closed by the `bors` bot while the issue remains:

```
Crate:     time
Version:   0.1.43
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.43
└── chrono 0.4.19
    ├── serde_with 2.0.0
```

**Comment by jonasbb** [comment]
The issue is closed because serde_with never depends on time v0.1, not even transitively.
chrono also does not use any of the vulnerable functions from time v0.1, see this comment: https://github.com/time-rs/time/issues/293#issuecomment-946382614, such that this is also a non-issue.

Quoting from the commit which closed #378 (https://github.com/jonasbb/serde_with/commit/d91731b5f5dc532ea2721bf861af7a064af9e47f):
> time v0.1 has a security advisory RUSTSEC-2020-0071
time is an optional dependency of chrono with the default features. The
dependency is not actually needed and can be avoided by not using the
default-features. Any crates which needs that time and chrono share the
Duration type can enable the feature themself.

serde_with does not active the `oldtime` feature of chrono. You must have another dependency which does this.
