### ISSUE TITLE
Skip serializing None with method?

### ISSUE THREAD

**Issue by letto4135** [jonasbb/serde_with#520]
Not sure if this fits here, but is there a way to optionally skip serializing None?
Example,
I have a query that is `select *` that I want every value to show up null or not.. But if `select id, location, whatever` I'd like only those 3 to be serialized... Seems like an easy thing to do, I'm probably just not looking at the problem the right way..

**Comment by jonasbb** [comment]
This question seems to belong to the https://github.com/serde-rs/serde/ repository and not here. Further, you are very sparse on details, so helping you is hard right now. Please check here: https://github.com/jonasbb/serde_with/blob/master/CONTRIBUTING.md#reporting-bugs

But I try to answer anyway: Skipping `None`s is already using a function `#[serde(skip_serializing_if = "Option::is_none")]`. If you need more flexibility, you can always write the `Serialize` implementation by hand. It is quite easy, and you can use the derived implementation as start.

If you are unfamiliar with serde, you should take a look over the documentation at https://serde.rs/ since it explains the available attributes and manual implementation.

**Comment by jonasbb** [comment]
> Yeah the skip_serializing_if isn't flexible enough. Trying to avoid writing my own serialize impl because it seems like something that should be able to be done already, or if not should be implemented, because being able to skip None sometimes and not others is useful in many situations.

It can be done already, by writing your own `Serialize`. There is no reason to shy away from it, if the derive stuff is not flexible enough. You definitely can use `skip_serializing_if` to "skip sometimes and not others". You can provide any function as argument there and the function can access whatever they want, be it global state, environment values, thread locals, etc.

I'm going to close the issue though, since problems with the derive macros cannot be fixed here.

**Comment by letto4135** [comment]
Any examples you know of that use actix_web and pass the request to serialize by chance?
This struct has 112 fields that all need to be serialized based on whether the request has a select= in the query string and what is in it if it does...

**Comment by letto4135** [comment]
Figured out a way to do it, but I don't like it. It's not pretty. Basically create a `Value` that has either `"result": MyStruct` or a `"result": Value` that has been paired down to selected fields..
