### ISSUE TITLE
Double option pattern with subserializer

### ISSUE THREAD

**Issue by Czocher** [jonasbb/serde_with#546]
Hello,
Is it possible to define a subserializer for the double-option pattern?

I have the following problem:
```rust
#[derive(Serialize, Deserialize, Debug)]
#[typeshare]
pub struct UserUpdateParams {
    ...
    #[serde(
        default,                                   
        skip_serializing_if = "Option::is_none",   
        with = "::serde_with::rust::double_option",
    )]
    #[serde(with = "rfc3339::option")]
    pub valid_until: Option<Option<OffsetDateTime>>,
}
```
This of course won't work since `with` is duplicated: `duplicate serde attribute 'serialize_with'`

Is there some way I can pass a subserializer for a double option?

**Comment by jonasbb** [comment]
Composition of serializers is not generally possible. The `serde_as`  stuff tries to address that for some cases. The double option pattern is not one which is generally usable here. Implementing `SerializeAs` for a hypothetical `DoubleOption<T>` would allow something like this, but it doesn't make sense, since the items inside a `Vec` cannot be skipped.

```rust
#[serde_as(as = "Vec<DoubleOption<_>>")]
data: Vec<Option<Option<i32>>>,
```

What could potentially work is treating the `DoubleOption<T>` similar to the existing [`As<T>`](https://docs.rs/serde_with/2.2.0/serde_with/struct.As.html), i.e., only the `T` uses `SerializeAs`, but the `DoubleOption` would only have `serialize`/`deserialize` functions compatible with `serde(with = "...")`. This could work since [`Rfc3339`](https://docs.rs/serde_with/2.2.0/serde_with/guide/serde_as_transformations/index.html#well-known-time-formats-for-offsetdatetime) is already an existing conversion type.
However, this would lose all the benefits of the `serde_as` macro. For example, you would need to write something like this and could not use the `_` as a placeholder and you would still need to carry the extra `default` and `skip_serializing_if` attributes anyway.

```rust
#[serde(
    default,                                   
    skip_serializing_if = "Option::is_none",   
	with = "DoubleOption<Vec<Same>>"
)]
data: Option<Option<Vec<i32>>>,
```

Due to the slight different usage compared to other `serde_as` things, this feels not worth it to me. But if you like it, you can always create it in your crates.
Another way is to create a `double_option_rfc3339`. The `double_option` functions are quite simple and should be easily adapted to `rfc3339`.

**Comment by Czocher** [comment]
@jonasbb thank you for your detailed response, it answered all my questions :).
