### ISSUE TITLE
Confusing/Incorrect PickFirst behavior

### ISSUE THREAD

**Issue by AdamSimpson** [jonasbb/serde_with#558]
Hi,
    I have created the following reproducer that demonstrates confusing (to me) behavior when using PickFirst. Can someone help me understand what is going on?

```
use indoc::indoc;
use serde::Deserialize;
use serde_with::{self, FromInto, OneOrMany, PickFirst};

#[derive(Deserialize, Debug)]
#[serde(untagged)]
pub enum SubChild {
    String(String),
    Vec(Vec<String>),
}

#[serde_with::serde_as]
#[derive(Deserialize, Debug)]
pub struct Child {
    #[serde_as(as = "Option<OneOrMany<_>>")]
    pub a: Option<Vec<SubChild>>,
    #[serde_as(as = "Option<OneOrMany<_>>")]
    pub b: Option<Vec<SubChild>>,
    #[serde_as(as = "Option<OneOrMany<_>>")]
    pub c: Option<Vec<SubChild>>,
}

impl From<Vec<SubChild>> for Child {
    fn from(from: Vec<SubChild>) -> Child {
        Child {
            a: Some(from),
            b: None,
            c: None,
        }
    }
}

#[serde_with::serde_as]
#[derive(Deserialize, Debug)]
pub struct Parent {
    #[serde_as(as = "Option<PickFirst<(_,FromInto<Vec<SubChild>>)>>")]
    pub child: Option<Child>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let form_yml = indoc! {"
    child:
      - foo
      - bar
    "};

    let deserialized: Parent = serde_yaml::from_str(form_yml)?;
    println!("{:#?}", deserialized);

    Ok(())
}
```

Cargo.toml
```
[package]
name = "serde_as_repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_with = { version = "2.2.0" }
indoc = "1.0"
```

The example unexpectedly produces:
```
Parent {
    child: Some(
        Child {
            a: Some(
                [
                    String(
                        "foo",
                    ),
                ],
            ),
            b: Some(
                [
                    String(
                        "bar",
                    ),
                ],
            ),
            c: None,
        },
    ),
}
```

When I expect:
```
Parent {
    child: Some(
        Child {
            a: Some(
                [
                    String(
                        "foo",
                    ),
                    String(
                        "bar",
                    ),
                ],
            ),
            b: None,
            c: None,
        },
    ),
}
```
If I switch the order of the `PickFirst` options(so `FromInto` is before `_`) it works as expected. If I remove `PickFirst` and use `#[serde_as(as = "Option<FromInto<Vec<SubChild>>>")]` it works as expected. If I remove the `#[serde_as]` within `Parent` I see ` Error("child: invalid type: sequence, expected struct Child"`, as expected. I am not sure why it doesn't work as expected though, as shown in the reproducer.

Thanks,
Adam

**Comment by jonasbb** [comment]
Internally `PickFirst` uses an untagged enum, so this very much seems like an instance of https://github.com/serde-rs/serde/issues/1183. However, I am more surprised that you get this error message (`invalid type: sequence, expected struct Child`) when not using `PickFirst`. That seems like something what should work.

First, this relates to internal buffering of serde. Deserialization works, with values in `a` and `b`, when using these types. So it can be triggered without `PickFirst`, just using untagged.
```rust
#[serde_with::serde_as]
#[derive(Deserialize, Debug)]
pub struct Parent {
    pub child: Option<Child>,
}

#[derive(Deserialize, Debug)]
#[serde(untagged)]
enum U {
    P(Parent)
}
```

The default serde_derive implements deserialization of structs in two ways: 1) map-based and 2) sequence-based. Map-based works assuming there is a key and the elements can be in any order. That is what people usually know and expect. However, the sequence model is usually a surprise. It matches the fields in order to the fields of the struct. Since the last field of `Child` is `Option`, it can be omitted without the deserialization failing. For example, this works:
```rust
#[derive(Debug, serde::Deserialize)]
struct Foo {
    a: i32,
    b: bool,
    c: String,
}

let f: Foo = serde_json::from_str(r#"[123, false, "Hi"]"#).unwrap();
dbg!(f);
```

Now what I cannot explain is why `serde_yaml` does not allow deserialization from a sequence directly. It used to allow it in version 0.8. You can test it with your example. Due to the internal buffering of untagged enums it is no longer `serde_yaml` which controls the behavior, but a serde-internal type, which does allow deserializing structs from sequences.

If you want a single sequence to deserialize as a list of `a`, then I think the correct change is to reorder the `PickFirst`, with the `FromInto` before the `_`.

**Comment by jonasbb** [comment]
This seems to be answered, so I am gonna close this issue.
