### ISSUE TITLE
[Feature request] Implement serde::Serialize and serde::Deserialize for serde_with::As

### ISSUE THREAD

**Issue by jrose-signal** [jonasbb/serde_with#624]
Recently I had a struct that looked like this:

```rust
#[serde_as]
#[derive(Serialize, Deserialize)
struct Example {
  #[serde_as(as = "serde_with::TimestampSeconds<i64>")]
  timestamp: SystemTime,
  // other properties
}
```

and I wanted to one-off serialize a separate timestamp "the same way". I did so roughly as follows:

```rust
let serializer = serde_data_format_provider::Serializer::default();
let serialized = serde_with::TimestampSeconds::<i64>::serialize_as(&timestamp, serializer)?;
```

This wasn't entirely satisfying. I could have made a one-off type for this:

```rust
#[serde_as]
#[derive(Serialize, Deserialize)]
#[serde(transparent)]
struct MyTimestamp {
  #[serde_as(as = "serde_with::TimestampSeconds<i64>")]
  timestamp: SystemTime,
}

let serialized = serde_data_format_provider::to_serialized(
  MyTimestamp { timestamp }
)?;
```

But what I reached for first (and found I couldn't use) was `serde_with::As`, which *almost* provides the right operations, but does not expose them.

```rust
// Does not work, but could!
let serialized = serde_data_format_provider::to_serialized(
  serde_with::As::<serde_with::TimestampSeconds<i64>>(timestamp)
)?;
```

This does not work, of course, because (1) `As` doesn't actually contain any data, and consequently (2) it doesn't implement Serialize. But it could: nothing in the current design of `As` prevents it, and it's clear what it would do.

EDIT: I just realized SerializeAs and DeserializeAs are generic, which means `As<T>` would become `As<T, I = ()>` or something, and that might not be perfectly compatible. But [it *should* be safe](https://doc.rust-lang.org/cargo/reference/semver.html#minor-changing-a-generic-type-to-a-more-generic-type).

**Comment by jonasbb** [comment]
Your first two options look ok to me and not overly complicated. Adding this to `As` is not the right solution. The problem is, that serializing and deserializing are not fully symmetrical. For example, you can serialize unsized types like `str`, but not deserialize them because serialization always uses references. This is presented in the two types [`serde_with::ser::SerializeAsWrap`](https://docs.rs/serde_with/latest/serde_with/ser/struct.SerializeAsWrap.html) and [`serde_with::de::DeserializeAsWrap`](https://docs.rs/serde_with/latest/serde_with/de/struct.DeserializeAsWrap.html). They implement `Serialize` and `Deserialize`, so should be able to full your gap.

**Comment by jrose-signal** [comment]
Aha, I didn't find those types. A bit more verbose than just `As`, but certainly usable. Thanks!

**Comment by jonasbb** [comment]
Glad they help you. You can always rename types while importing them to keep the names short:

```rust
use serde_with::ser::SerializeAsWrap as Short;
```
