### ISSUE TITLE
Using `TimestampMilliSeconds` to serialize `DateTime<Utc>` differs from calling `DateTime<Utc>::timestamp_millis`

### ISSUE THREAD

**Issue by guidomb** [jonasbb/serde_with#625]
Sometimes, this happens randomly, when serializing a `DateTime<Utc>` using `TimestampMilliSeconds` the resulting output value end-ups with an added 1 millisecond compared to the value obtained by calling `DateTime<Utc>::timestamp_millis`. I would say this happens 1 out 4 times.

Rust version: `rustc 1.69.0 (84c898d65 2023-04-16)`

Current crates versions:

```
chrono = "0.4.26"
serde_with = { version = "3.0.0", features = ["chrono_0_4"]}
```

**Comment by jonasbb** [comment]
Thanks for the report. That is very interesting. `TimestampMilliSeconds` does not use `timestamp_millis`. I found a case. The first is the debug representation of `DateTime`, then `timestamp_millis`, lastly `TimestampMilliSeconds`.

```text
2023-07-26T21:57:09.838751504Z
"1690408629838"
"1690408629839"
```

The difference occurs because `TimestampMilliSeconds` rounds the value. This is called out in the example https://docs.rs/serde_with/3.1.0/serde_with/struct.TimestampSeconds.html. Granted, that could be mentioned in the text description too.

```rust
use chrono::DateTime;
use chrono::Utc;

#[serde_with::serde_as]
#[derive(serde::Serialize)]
#[serde(transparent)]
struct W(#[serde_as(as = "serde_with::TimestampMilliSeconds")] DateTime<Utc>);

fn main() {
    let dt = Utc::now();
    println!("{dt:?}");
    println!(r#""{}""#, dt.timestamp_millis());
    let j = serde_json::to_string(&W(dt)).unwrap();
    println!("{j:?}");
}
```
