### ISSUE TITLE
[Help Request] Use both true/false and 0/1 as bool parameter

### ISSUE THREAD

**Issue by piavgh** [jonasbb/serde_with#631]
Hi @jonasbb 

I have a struct

```rust
use serde_with::{serde_as, BoolFromInt, PickFirst};
...

#[serde_as]
#[derive(Debug, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct GetRouteEncodeParams {
    pub chain: String,
    pub token_in: String,
    pub token_out: String,
    pub amount_in: String,
    #[serde_as(as = "PickFirst<(_,BoolFromInt)>")]
    pub save_gas: bool,
    pub recipient: String,
}
```

If I use `#[serde_as(as = "PickFirst<(_,BoolFromInt)>")]` like this, both "true/false" or "0/1" are NOT working for the param `save_gas`

For example, if I send from Postman 

```
curl --location 'localhost:8000/api/route/encode?chain=arbitrum&tokenIn=0x82af49447d8a07e3bd95bd0d56f35241523fbab1&tokenOut=0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9&amountIn=100000000000000000000&saveGas=0&recipient=0x6BB030922F22FEd1038951BcaF6Ea40983B49123'
```

it can not even parse the struct (I use `rename_all = "camelCase"` so from Postman I use camelCase)

But if I use only `#[serde_as(as = "PickFirst<(_,)>")]` or `#[serde_as(as = "BoolFromInt")]`, it works properly (but only for "true/false" OR "0/1", not both cases as I expected)

How can I solve this problem?
Thanks

**Comment by jonasbb** [comment]
If `PickFirst<(_,)>` works but `PickFirst<(_,BoolFromInt)>` does not, than it sounds to me like this is another instance of https://github.com/serde-rs/serde/issues/1183. I cannot help you further, unless you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), since you don't mention which data format and libraries you are using. It might be necessary for you to handwrite the deserialize implementation.
