### ISSUE TITLE
Using serde_as with tuple structs

### ISSUE THREAD

**Issue by danwilliams** [jonasbb/serde_with#648]
For "standard" structs (i.e. those with multiple members), `serde_as` is working fine for me. If I have a struct member that I want to serialise and deserialise in a particular way, I can do this:

```rust
#[serde_as]
#[derive(Deserialize, Serialize)]
pub struct BigStruct{
	#[serde_as(as = "DisplayFromStr")]
	pub status: LittleStruct,
}

pub struct LittleStruct(Vec<u8>);
```

However, this only applies to `LittleStruct` when `LittleStruct` is a member of `BigStruct`.

Ideally, I want to apply the behaviour directly to `LittleStruct`. Something like this:

```rust
#[derive(Deserialize, Serialize)]
pub struct BigStruct{
	pub status: LittleStruct,
}

#[serde_as(as = "DisplayFromStr")]
#[derive(Deserialize, Serialize)]
pub struct LittleStruct(Vec<u8>);
```

However, that does not work, as the "as =" part of `serde_as` needs to be inside the struct.

I have searched around and read through all the documentation and not seen examples of this, nor any mention of tuple structs. There was one closed ticket which touched on the subject but wasn't the same.

Is this a bug, missing use case implementation, or by design? Is there any way to achieve this goal, or am I stuck with the options of leaving it like it is in the first example, or using serde directly if I want to apply the functionality directly to `LittleStruct`?

**Comment by jonasbb** [comment]
The same way you cannot use serde's `with` attribute on a container (i.e., a struct), you cannot use the `serde_as` attribut either. That is intentional.

In this specific case I think you are looking for [`SerializeDisplay`](https://docs.rs/serde_with/latest/serde_with/derive.SerializeDisplay.html) and [`DeserializeFromStr`](https://docs.rs/serde_with/latest/serde_with/derive.DeserializeFromStr.html). They are derive macros that replace the existing `Deserialize` and `Serialize` ones, while converting the struct value to/from a string representation.

For completeness, I want to add that in serde there is a big difference between these two things.

```rust
// A
#[serde_as(as = "DisplayFromStr")]
pub struct LittleStruct(Vec<u8>);

// B
pub struct LittleStruct(#[serde_as(as = "DisplayFromStr")] Vec<u8>);
```

Variant A is invalid (but exists similar on enum variants), but B is valid and supported by `serde_with`. Presumably you do not want variant B here, since there is no `Display` implementation for `Vec<u8>`.
