### ISSUE TITLE
Support for serde_as attached to a struct decl (not a field) - multi-field struct with canonical representation via a primitive (e.g. String)

### ISSUE THREAD

**Issue by Sajjon** [jonasbb/serde_with#677]
I find myself in the need for what Heinz / @Licenser brought in serde repo in https://github.com/serde-rs/serde/issues/1689 

I a bit new to Rust and the world of Serde and `serde_with` so hopefully what I want is possible using either Serde or `serde_with` today already! Here is my usecase (in open source repo, see [AccountAddress](https://github.com/Sajjon/RadixWalletKit/blob/develop/profile/src/v100/address/account_address.rs)):

```rust
pub struct AccountAddress {
    /// Human readable address of an account. Always starts with `"account_"``, for example:
    ///
    /// `account_rdx16xlfcpp0vf7e3gqnswv8j9k58n6rjccu58vvspmdva22kf3aplease`
    ///
    /// Most commonly the user will see this address in its abbreviated
    /// form which is:
    ///
    /// `acco...please`
    ///
    /// Addresses are checksummed, as per Bech32. **Only** *Account* addresses starts with
    /// the prefix `account_`.
    pub address: String,

    /// The network this account address is tied to, i.e. which was used when a public key
    /// hash was used to bech32 encode it. This means that two public key hashes will result
    /// in two different account address on two different networks.
    pub network_id: NetworkID,
}
```

The `network_id` is contained inside of the `address`, so like Heinz scenario, it is akin to a computed property. When we serialize the `AccountAddress` we need it to be just the address, not an object (since it is not needed, thus much more compact).

Today I have manually implemented this:

```rust
impl Serialize for AccountAddress {
    fn serialize<S>(&self, serializer: S) -> Result<<S as Serializer>::Ok, <S as Serializer>::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&self.address)
    }
}

impl<'de> serde::Deserialize<'de> for AccountAddress {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<AccountAddress, D::Error> {
        let s = String::deserialize(d)?;
        AccountAddress::try_from_bech32(&s).map_err(de::Error::custom)
    }
}
```

If feels... like this is a good use case for `serde_with` crate, using `serde_as` on the struct itself!

```rust
#[serde_as]
#[derive(Serialize, Deserialize)]
#[serde_as(as = "DisplayFromStr")]
pub struct AccountAddress {
    pub address: String,
    pub network_id: NetworkID,
}
impl Display for AccountAddres { ... }
impl FromStr for AccountAddres { ... }
```

But that seems to not work.

I've tried marking it `#[serde(transparent)]` as well, but that does not work...

What do you think?

**Comment by jonasbb** [comment]
If you want custom serialization behavior for a full struct it is usually better to implement it manually. In this case I feel using `DisplayFromStr` would not save you much, since now you require `Display` and `FromStr` for the custom logic. The `FromStr` implementation will look very similar to the `Deserialize` implementation, with the main difference, that you get a `&str` from the beginning, but the `Deserialize` implementation can be more flexible if you need ownership of a `String`.

For the specific case of serializing the whole struct to a string, there are the two derive macros [`SerializeDisplay`](https://docs.rs/serde_with/latest/serde_with/derive.SerializeDisplay.html) and [`DeserializeFromStr`](https://docs.rs/serde_with/latest/serde_with/derive.DeserializeFromStr.html). A general `serde_as` on the whole struct is not as simple, since serde does not permit using `serde(with = "")` on structs.

**Comment by Sajjon** [comment]
@jonasbb Thank you, `SerializeDisplay` and `DeserializeFromStr` was exactly what I was looking for! 

I wanna propose promoting them a bit more in your docs, they are not documented in the root of `serde_with` - https://docs.rs/serde_with/3.4.0/serde_with/

<img width="1016" alt="Screenshot 2024-01-15 at 08 16 10" src="https://github.com/jonasbb/serde_with/assets/864410/fb01b0f9-1ffb-48c4-a459-708ab607896b">

Why I missed them (I am also quite to to Rust so not as used reading docs as a veteran...)
