### ISSUE TITLE
gate `serde_as` behind `is_human_readable`

### ISSUE THREAD

**Issue by irriden** [jonasbb/serde_with#687]
In the example from the docs reproduced below:

```
#[serde_as]
#[derive(Deserialize, Serialize)]
struct Foo {
    // Serialize with Display, deserialize with FromStr
    #[serde_as(as = "DisplayFromStr")]
    bar: u8,
}
```

I am wondering if it would be possible to expand it to say:

use `Display`, `FromStr` only if `Serializer::is_human_readable`

**Comment by jonasbb** [comment]
Right now, you will need to write a custom implementation for your `Foo` struct to use `is_human_readable`. Inside that implementation, you can make use of all of the `serde_as` types. 

I think it is possible to have something like:

```rust
#[serde_as]
#[derive(Deserialize, Serialize)]
struct Foo {
    // Serialize with Display, deserialize with FromStr
    #[serde_as(as = "IfIsHumanReadable<DisplayFromStr, _>")]
    bar: u8,
}
```

This new type would work like an if-else-construct, using the `is_human_readable` function to branch between the two options. For human readable formats it would use the first format (here `DisplayFromStr`) otherwise use the fallback (here `_`, thus using the `u8` implementations of `Serialize`/`Deserialize`). The second type could default to `_`, such that writing `IfIsHumanReadable<DisplayFromStr>` works too, like an if without else block.
