### ISSUE TITLE
can I combine `#[serde(default = "default_template")]` and `#[serde_as(deserialize_as = "DefaultOnNull")]`

### ISSUE THREAD

**Issue by LuckyTurtleDev** [jonasbb/serde_with#748]
Something like this would be nice
```
#[serde(default = "default_template")]
#[serde_as(deserialize_as = "DefaultOnNull")]
pub template: String,
```

**Comment by jonasbb** [comment]
I don't think this is possible. The part after `deserialize_as` needs to be a type/function that handles the `null` can call the provided function. You can do such parametrization using types, but functions are not types, but values. Basically, you cannot have a `DefaultOnNull<default_template>` or a `default_on_null::<default_template>()`. As such, I don't know how to make `DefaultOnNull` aware to call `default_template`, since it cannot store that value anywhere.
